export const rectangles = [
  {
    type: 'rectangle',
    density: 0.7,
    width: 32,
    height: 40,
    xScale: 0.25,
    yScale: 0.25,
    url: '/assets/images/logo/archlinux.svg',
  },
  {
    type: 'rectangle',
    density: 0.7,
    width: 55,
    height: 45,
    xScale: 0.25,
    yScale: 0.25,
    url: '/assets/images/logo/kickAOL.png',
  },
  {
    type: 'rectangle',
    density: 0.7,
    width: 55,
    height: 64,
    xScale: 0.25,
    yScale: 0.25,
    url: '/assets/images/logo/logoGrunt.png',
  },
  {
    type: 'rectangle',
    density: 0.8,
    width: 29,
    height: 64,
    xScale: 0.25,
    yScale: 0.25,
    url: '/assets/images/logo/logoGulp.png',
  },
  {
    type: 'rectangle',
    density: 0.8,
    width: 38,
    height: 64,
    xScale: 0.25,
    yScale: 0.25,
    url: '/assets/images/logo/logoHTML5.png',
  },
  {
    type: 'rectangle',
    density: 0.4,
    width: 50,
    height: 50,
    xScale: 0.25,
    yScale: 0.25,
    url: '/assets/images/logo/logoJavascript.png',
  },
  {
    type: 'rectangle',
    density: 0.5,
    width: 60,
    height: 22,
    xScale: 0.25,
    yScale: 0.25,
    url: '/assets/images/logo/logoJekyll.png',
  },
  {
    type: 'rectangle',
    density: 0.6,
    width: 50,
    height: 52,
    xScale: 0.25,
    yScale: 0.25,
    url: '/assets/images/logo/logoMarionette.png',
  },
  {
    type: 'rectangle',
    density: 0.7,
    width: 64,
    height: 18,
    xScale: 0.25,
    yScale: 0.25,
    url: '/assets/images/logo/logoMongoDB.png',
  },
  {
    type: 'rectangle',
    density: 0.8,
    width: 62,
    height: 32,
    xScale: 0.25,
    yScale: 0.25,
    url: '/assets/images/logo/logoMySQL.png',
  },
  {
    type: 'rectangle',
    density: 0.6,
    width: 52,
    height: 32,
    xScale: 0.25,
    yScale: 0.25,
    url: '/assets/images/logo/logoNodeJS.png',
  },
  {
    type: 'rectangle',
    density: 0.8,
    width: 60,
    height: 21,
    xScale: 0.25,
    yScale: 0.25,
    url: '/assets/images/logo/logoNpm.png',
  },
  {
    type: 'rectangle',
    density: 0.7,
    width: 60,
    height: 32,
    xScale: 0.25,
    yScale: 0.25,
    url: '/assets/images/logo/logoPHP.png',
  },
  {
    type: 'rectangle',
    density: 0.7,
    width: 49,
    height: 62,
    xScale: 0.25,
    yScale: 0.25,
    url: '/assets/images/logo/logoRubyOnRails.png',
  },
  {
    type: 'rectangle',
    density: 0.6,
    width: 62,
    height: 48,
    xScale: 0.25,
    yScale: 0.25,
    url: '/assets/images/logo/logoSass.png',
  },
];


export const circles = [
  {
    type: 'circle',
    density: 0.025,
    radius: 30,
    xScale: 0.25,
    yScale: 0.25,
    url: '/assets/images/logo/logoC.png',
  },

  {
    type: 'circle',
    density: 0.025,
    radius: 30,
    xScale: 0.25,
    yScale: 0.25,
    url: '/assets/images/logo/logoAMP.png',
  },
  {
    type: 'circle',
    density: 0.05,
    radius: 30,
    xScale: 0.25,
    yScale: 0.25,
    url: '/assets/images/logo/logoAtom.png',
  },
  {
    type: 'circle',
    density: 0.015,
    radius: 31,
    xScale: 0.25,
    yScale: 0.25,
    url: '/assets/images/logo/logoBower.png',
  },
  {
    type: 'circle',
    density: 0.05,
    radius: 29,
    xScale: 0.25,
    yScale: 0.25,
    url: '/assets/images/logo/logoChrome.png',
  },
  {
    type: 'circle',
    density: 0.015,
    radius: 24,
    xScale: 0.25,
    yScale: 0.25,
    url: '/assets/images/logo/logoWordpress.png',
  },
  {
    type: 'circle',
    density: 0.05,
    radius: 28,
    xScale: 0.25,
    yScale: 0.25,
    url: '/assets/images/logo/logoYeoman.png',
  },
];
